import {Texturina} from 'next/font/google'
import './globals.css'


const rubik = Texturina({ subsets: ['latin'] })

export const metadata = {
  title: 'HABEEB portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
           <link rel="icon" href="favicon-32x32.png"/>
      </head>
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
